if(${USE_PREBUILT_LIBRARIES})
  message(STATUS "=== SPDLOG (Prebuilt) ===")
  include("${CMAKE_CURRENT_LIST_DIR}/prebuilt/Prebuilt.cmake")
else()
  message(STATUS "=== SPDLOG (Source) ===")
  set(SPDLOG_BUILD_SHARED OFF CACHE BOOL "Build shared library" FORCE)
  set(SPDLOG_ENABLE_PCH ON CACHE BOOL "Build static or shared library using precompiled header to speed up compilation time" FORCE)
  set(SPDLOG_NO_EXCEPTIONS ON CACHE BOOL "Compile with -fno-exceptions. Call abort() on any spdlog exceptions" FORCE)
  add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/source")
endif()

message(STATUS "")