option(ENABLE_CPPCHECK "Enable static analysis with cppcheck" OFF)
option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" OFF)

if(ENABLE_CPPCHECK)
    find_program(CPPCHECK cppcheck)
    if(CPPCHECK)
        message(STATUS "Using Cppcheck")
        message(STATUS "${CMAKE_CXX_CPPCHECK}")
    else()
        message(WARNING "Cppcheck not found")
    endif()
endif()

if(ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy)
    if(CLANGTIDY)
        message(STATUS "Using Cppcheck")
        set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY})
    else()
        message(WARNING "clang-tidy not found")
    endif()
endif()
